server:
  port: 30001
---  
kafka:
  topic:
    product: product-event-topic
    order: order-event-topic    
    member: member-event-topic
---    
kafka:
  bootstrap:
    servers: localhost:9092,localhost:9093,localhost:9094
---
spring:
  application:
    name: start-point
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
    
spring.servlet.multipart.maxFileSize: 10MB
spring.servlet.multipart.maxRequestSize: 10MB

aws:
  access-key: 'example'
  secret-key: 'example'
  s3:
    bucket: 'bucket-name'


