version: '2.1'
services: 

  mysql:
    image: mysql:latest
    container_name: mysql_host
    environment:
        MYSQL_DATABASE: "system"
        MYSQL_USER: "pilot"
        MYSQL_PASSWORD: "pilot"
        MYSQL_ROOT_PASSWORD: "root"    
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    command: --default-authentication-plugin=mysql_native_password
    volumes:
        - "./mysql/init/:/docker-entrypoint-initdb.d/"
        - "./mysql/data:/var/lib/mysql"
        - "./mysql/conf/mysqld.conf:/etc/mysql/mysql.conf.d/mysqld.cnf"
    ports:
        - 3306:3306