version: '3'
# 20200914
services:
    mysql:
        image: mysql:5.7
        container_name: mysql_host
        environment:
            MYSQL_DATABASE: "system"
            MYSQL_USER: "pilot"
            MYSQL_PASSWORD: "pilot"
            MYSQL_ROOT_PASSWORD: "root"    
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - "./mysql/init/:/docker-entrypoint-initdb.d/"
            - "./mysql/data:/var/lib/mysql"
            - "./mysql/conf/mysqld.conf:/etc/mysql/mysql.conf.d/mysqld.cnf"
        ports:
            - 3306:3306
        networks:
            - mysqlnetwork
 
    redis-server:
        restart: always
        image: redis:latest
        container_name: redis-server
        command: /bin/bash -c 'redis-server --appendonly yes'
        sysctls:
            - net.core.somaxconn=65535
        ports:
            - "6379:6379"
        volumes:
            - ./redis:/data
        networks:
            - mysqlnetwork                   
networks:
    mysqlnetwork:
        driver: bridge