server:
  port: 8087

spring:
    mvc:
     view:
        prefix: /WEB-INF/views/
        suffix: .jsp
     static-path-pattern: /resources/** 
---
server:
  ssl:
    enabled: false
    key-store: ./ca/rcs_keystore.jks 
    key-store-password: testtest
    key-password: testtest
    key-alias: tomcat
    trust-store: ./ca/rcs_cacerts.jks
    trust-store-password: testtest
    
spring:
  profiles: local
  application:
    name: bo
    
  
redis:
  mode: standalone  # standalone or sentinels or cluster
  master: mymaster
  db_num: 15  # local only (spring.profile=local)
  password :
  standalone:
      host: 127.0.0.1
      port: 6379
  sentinels:
      host: 127.0.0.1, 127.0.0.2
      port: 26381, 26382
  cluster:
      host: 127.0.0.1
      port: 7000, 7001, 8001
  timeout:
      cmdSec : 10  #sec      
