version: '2'

services:

  fluentd:
    build: ./
    container_name: log-fluentd
    volumes:
      - /home/ec2-user/apps/fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"

  elasticsearch:
    image: elasticsearch:6.8.5
    container_name: log-elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" 
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:6.8.5
    container_name: log-kubana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
